[package]
name = "cpu-raytracing-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "^0.18.0"
rayon = "^1.10.0"
rand = "^0.8.5"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
